/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************


// We configurate GPIO pin with REGISTER bits configurations.
// In this example we blink our LED-->>PORTD pin  13
*/


#include <stdint.h>
#include"gpio.h"
#include"rng.h"


//uint32_t g_random_number;

void HASH_RNG_IRQHandler(void)
{
	if( ((RNG->SR & RNG_CEIS)==0) && ((RNG->SR & RNG_SEIS)==0) && ((RNG->SR & RNG_DRDY) ==1 ))
	{
		//g_random_number=RNG->DR;
		RNG->CR &= ~IE;
		RNG->CR &= ~RNGEN;
		nvic_irqno_desable(IRQ_HASH_RNG);
	}
	else
	{
		//error
		if(RNG->SR & RNG_CEIS)
			RNG->CR &= ~RNG_CEIS;
		if(RNG->SR & RNG_SEIS)
			RNG->CR &= ~RNG_SEIS;

		RCC->AHB2RSTR |= RNGRST;
		RCC->AHB2RSTR &= ~RNGRST;

		RCC->CR=PLLON;
		while(!(RCC->CR & PLLREADY));
		RNG->CR |= RNGEN;
		RNG->CR |= IE;
	}
}
int main(void)
{


	GPIO_Handle_t GPIO_PIN_BLUE={GPIOD,{GPIO_PIN_NO_15,
										GPIO_MODE_OUT,
										GPIO_OTYPE_PP,
										GPIO_NO_PUPD,
										GPIO_SPEED_MEDIUM}
										};
	gpio_init(&GPIO_PIN_BLUE);

	GPIO_Handle_t GPIO_PIN_RED={GPIOD,{GPIO_PIN_NO_14,
											GPIO_MODE_OUT,
											GPIO_OTYPE_PP,
											GPIO_NO_PUPD,
											GPIO_SPEED_MEDIUM}
											};
	gpio_init(&GPIO_PIN_RED);

	GPIO_Handle_t GPIO_PIN_ORANGE={GPIOD,{GPIO_PIN_NO_13,
												GPIO_MODE_OUT,
												GPIO_OTYPE_PP,
												GPIO_NO_PUPD,
												GPIO_SPEED_MEDIUM}
												};
		gpio_init(&GPIO_PIN_ORANGE);

	GPIO_Handle_t GPIO_PIN_GREEN={GPIOD,{GPIO_PIN_NO_12,
													GPIO_MODE_OUT,
													GPIO_OTYPE_PP,
													GPIO_NO_PUPD,
													GPIO_SPEED_MEDIUM}
													};
	gpio_init(&GPIO_PIN_GREEN);




	rng_init();

	while(1){
		rng_init();
		toggle_board_random_led();
	}
}



