/*
 * stm32f407xx.h
 *
 *  Created on: Dec 17, 2023
 *      Author: ramazan
 */

#ifndef STM32F407XX_H_
#define STM32F407XX_H_
#include<stdint.h>


//Bus Base Addresses
#define PERIPHERAL_BASE_ADDR 		0x40000000U
#define APB1PERIPHERAL_BASE_ADDR	PERIPHERAL_BASE_ADDR
#define APB2PERIPHERAL_BASE_ADDR 	0x40010000U
#define AHB1PERIPHERAL_BASE_ADDR	0x40020000U
#define AHB2PERIPHERAL_BASE_ADDR	0x50050000U

//APB1 Bus Base Addresses
#define TIM2_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x00)
#define TIM3_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x400)
#define TIM4_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x800)
#define TIM5_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0xC00)
#define TIM6_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x1000)
#define TIM7_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x1400)
#define TIM12_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x1800)
#define TIM13_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x1C00)
#define RTCBKP_BASEADRR 			(APB1PERIPHERAL_BASE_ADDR+0x2800)
#define WWDG_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x2C00)
#define IWDG_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x3000)
#define I2S2_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x3400)
#define SPI2_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x3800)
#define SPI3_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x3C00)
#define IS2S3_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x4000)
#define UART2_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x4400)
#define UART3_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x4800)
#define UART4_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x4C00)
#define UART5_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x5000)
#define I2C1_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x5400)
#define I2C2_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x5800)
#define I2C3_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x5C00)
#define CAN1_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x6400)
#define CAN2_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x6800)
#define PWR_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x7000)
#define DAC_BASEADRR 				(APB1PERIPHERAL_BASE_ADDR+0x7400)

//APB2 Bus Base Addresses
#define TIM1_BASEADRR 				(APB2PERIPHERAL_BASE_ADDR+0x00)
#define TIM8_BASEADRR 				(APB2PERIPHERAL_BASE_ADDR+0x400)
#define USART1_BASEADRR 			(APB2PERIPHERAL_BASE_ADDR+0x1000)
#define USART6_BASEADRR 			(APB2PERIPHERAL_BASE_ADDR+0x1400)
#define ADCI_2_3_BASEADRR			(APB2PERIPHERAL_BASE_ADDR+0x2000)
#define SDIO_BASEADRR 				(APB2PERIPHERAL_BASE_ADDR+0x2C00)
#define SPI1_BASEADRR 				(APB2PERIPHERAL_BASE_ADDR+0x3000)
#define SYSCFG_BASEADRR				(APB2PERIPHERAL_BASE_ADDR+0x3800)
#define EXTI_BASEADRR 			    (APB2PERIPHERAL_BASE_ADDR+0x3C00)
#define TIM9_BASEADRR 				(APB2PERIPHERAL_BASE_ADDR+0x4000)
#define TIM10_BASEADRR 				(APB2PERIPHERAL_BASE_ADDR+0x4400)
#define TIM11_BASEADRR 				(APB2PERIPHERAL_BASE_ADDR+0x4800)

//AHB1 Bus Base Addresses
#define GPIOA_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x00)
#define GPIOB_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x400)
#define GPIOC_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x800)
#define GPIOD_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x0C00)
#define GPIOE_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x1000)
#define GPIOF_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x1400)
#define GPIOG_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x1800)
#define GPIOH_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x1C00)
#define GPIOI_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x2000)
#define CRC_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x3000)
#define RCC_BASEADRR 				(AHB1PERIPHERAL_BASE_ADDR+0x3800)
#define FLASH_INT_BASEADRR 			(AHB1PERIPHERAL_BASE_ADDR+0x3C00)
#define BKPSRAM_BASEADRR 			(AHB1PERIPHERAL_BASE_ADDR+0x4000)
#define DMA1_BASEADRR 			    (AHB1PERIPHERAL_BASE_ADDR+0x6000)
#define DMA2_BASEADRR 			    (AHB1PERIPHERAL_BASE_ADDR+0x6400)
#define ETHERNET_MAC_BASEADRR 		(AHB1PERIPHERAL_BASE_ADDR+0x8000)
#define USB_OTG_HS_BASEADRR 		(AHB1PERIPHERAL_BASE_ADDR+0x40000)
#define USB_OTG_FS_BASEADRR 		(0x50000000)

//AHB2 Bus Base Addresses
#define DCMI_BASEADRR 				(AHB2PERIPHERAL_BASE_ADDR+0x00)
#define RNG_BASEADRR 				(AHB2PERIPHERAL_BASE_ADDR+0x10800)

//IRQ NUMBERS
#define IRQ_EXTI0		6
#define IRQ_EXTI1		7
#define IRQ_EXTI2		8
#define IRQ_EXTI3		9
#define IRQ_EXTI5_9		23
#define IRQ_EXTI5_10	40
#define IRQ_HASH_RNG    80

//RCC registers
typedef struct{
	volatile uint32_t CR;
	volatile uint32_t PLLCFGR;
	volatile uint32_t CFGR;
	volatile uint32_t CIR;
	volatile uint32_t AHB1RSTR;
	volatile uint32_t AHB2RSTR;
	volatile uint32_t AHB3RSTR;
	uint32_t RESERVED0;
	volatile uint32_t APB1RSTR;
	volatile uint32_t APB2RSTR;
	uint32_t RESERVED1[2];
	volatile uint32_t AHB1ENR;
	volatile uint32_t AHB2ENR;
	volatile uint32_t AHB3ENR;
	uint32_t RESERVED2;
	volatile uint32_t APB1ENR;
	volatile uint32_t APB2ENR;
	uint32_t RESERVED3[2];
	volatile uint32_t AHB1LPENR;
	volatile uint32_t AHB2LPENR;
	volatile uint32_t AHB3LPENR;
	uint32_t RESERVED4;
	volatile uint32_t APB1LP;
	volatile uint32_t APB2LP;
	uint32_t RESERVED5[2];
	volatile uint32_t BDCR;
	volatile uint32_t CSR;
	uint32_t RESERVED6[2];
	volatile uint32_t SSCGR;
	volatile uint32_t PLLI2SC;
}RCC_RegDef_t;

//GPIO registers
typedef struct{
	volatile uint32_t MODER;
	volatile uint32_t OTYPER;
	volatile uint32_t OSPEEDR;
	volatile uint32_t PUPDR;
	volatile uint32_t IDR;
	volatile uint32_t ODR;
	volatile uint32_t BSRR;
	volatile uint32_t LCKR;
	volatile uint32_t AFRL[2];
}GPIO_RegDef_t;

typedef struct{
	volatile uint32_t IMR;
	volatile uint32_t EMR;
	volatile uint32_t RTSR;
	volatile uint32_t FTSR;
	volatile uint32_t SWIER;
	volatile uint32_t PR;
}EXTI_RegDef_t;

typedef struct{
	volatile uint32_t MEMRMP;
	volatile uint32_t PMC;
	volatile uint32_t EXTICR[4];
	uint32_t RESERVED[2];
	volatile uint32_t  CMPCR;
}SYSCFG_RegDef_t;

typedef struct{
	volatile uint32_t CR;
	volatile uint32_t SR;
	volatile uint32_t DR;
}RNG_RegDef_t;

//RCC CLOCK MAPPING
#define RCC   		((RCC_RegDef_t*)RCC_BASEADRR)

//EXTI REGISTER MAPPING
#define EXTI	   ((EXTI_RegDef_t*)EXTI_BASEADRR)

//SYSCFG Memory Mapping
#define SYSCFG		((SYSCFG_RegDef_t*)SYSCFG_BASEADRR)

//RNG MEMORY MAPPING
#define RNG			((RNG_RegDef_t*)RNG_BASEADRR)

//RNG CLOCK Enable
#define RNG_CLOCK_ENABLE()   (RCC->AHB2ENR |= (1<<6))

//GPIO CLOCK REGISTER ENABLE
#define GPIOA_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<0))
#define GPIOB_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<1))
#define GPIOC_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<2))
#define GPIOD_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<3))
#define GPIOE_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<4))
#define GPIOF_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<5))
#define GPIOG_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<6))
#define GPIOH_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<7))
#define GPIOI_CLOCK_ENABLE()	(RCC->AHB1ENR |= (1u<<8))

#define SYSCFG_CLOCK_ENABLE()   (RCC->APB2ENR |= (1U<<14))

//GPIO REGISTER MAPPING
#define GPIOA ((GPIO_RegDef_t*)GPIOA_BASEADRR)
#define GPIOB ((GPIO_RegDef_t*)GPIOB_BASEADRR)
#define GPIOC ((GPIO_RegDef_t*)GPIOC_BASEADRR)
#define GPIOD ((GPIO_RegDef_t*)GPIOD_BASEADRR)
#define GPIOE ((GPIO_RegDef_t*)GPIOE_BASEADRR)
#define GPIOF ((GPIO_RegDef_t*)GPIOF_BASEADRR)
#define GPIOG ((GPIO_RegDef_t*)GPIOG_BASEADRR)
#define GPIOH ((GPIO_RegDef_t*)GPIOH_BASEADRR)
#define GPIOI ((GPIO_RegDef_t*)GPIOI_BASEADRR)


#endif /* STM32F407XX_H_ */
